modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU LGPL 3.0"

[[mods]]
modId = "ordinarytweaks"
version = "${version}"
displayName = "SomeOrdinaryTweaks"
logoFile = "icon.png"
authors = "Maheesha"
description = '''
A forge port of SomeOrdinaryTweaks
'''

[[dependencies.ordinarytweaks]]
modId = "cloth_config"
mandatory = true
versionRange = "[7.0,)"
ordering = "NONE"
side = "CLIENT"


